version: "3.9"

services:
    backend:
        image: che:latest
        container_name: che
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - "8002:80"
        volumes:
            - ..:/che-sandbox
        extra_hosts:
            - "host.docker.internal:host-gateway"
